build:
    nodes:
        analysis:
            project_setup:
                override: true
            tests:
                override: [php-scrutinizer-run]
    environment:
        php: 7.3
        mysql: 5.6

filter:
    excluded_paths:
        - '3rdparty/*'
        - 'js/jquery*'

imports:
    - javascript
    - php
