# Jekyll configuration
repository: rello/audioplayer
theme: jekyll-theme-cayman
timezone: Europe/Berlin
name: "Audio Player Editor"
title: "Audio Player Editor"
description: "Audio Player for Nextcloud and ownCloud"
url: "https://rello.github.io/audioplayer"
author: "Marcel Scherello"
